resource_registry:
  OS::TripleO::Compute::Net::SoftwareConfig: /home/stack/templates/nic-configs/computeovsdpdk.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/templates/nic-configs/controller.yaml
  OS::TripleO::NodeUserData: /home/stack/templates/first-boot.yaml
  OS::TripleO::NodeExtraConfigPost: /home/stack/templates/post-install.yaml
  OS::TripleO::AllNodes::Validation: /home/stack/templates/dummy_all_nodes-validation.yaml

parameter_defaults:
  PingTestIps: ''
  ControlPlaneDefaultRoute: "172.18.0.1"
  ControlPlaneSubnetCidr: "24"
  DnsServers: ['8.8.8.8','8.8.4.4']
  EC2MetadataIp: "172.18.0.1"
  #ExternalAllocationPools: [{'start': '172.18.1.150', 'end': '172.18.1.200'}]
  #ExternalNetCidr: "172.18.1.0/24"
  #ExternalNetworkVlanID: 10
  #NeutronExternalNetworkBridge: ""
  #ExternalInterfaceDefaultRoute: "172.18.1.1"

  InternalApiNetCidr: 10.10.100.0/24
  StorageNetCidr: 10.10.101.0/24
  StorageMgmtNetCidr: 10.10.102.0/24
  TenantNetCidr: 10.10.103.0/24
  InternalApiNetworkVlanID: 100
  StorageNetworkVlanID: 101
  StorageMgmtNetworkVlanID: 102
  InternalApiAllocationPools: [{'start': '10.10.100.10', 'end': '10.10.100.200'}]
  StorageAllocationPools: [{'start': '10.10.101.10', 'end': '10.10.101.200'}]
  StorageMgmtAllocationPools: [{'start': '10.10.102.10', 'end': '10.10.102.200'}]
  TenantAllocationPools: [{'start': '10.10.103.10', 'end': '10.10.103.200'}]

  OvercloudComputeFlavor: "compute"
  OvercloudControlFlavor: "control"
  ComputeCount: 2

  NeutronBridgeMappings: "datacentre:br-ex"
  NeutronFlatNetworks: "datacentre"
  NeutronNetworkType: "gre"
  NeutronTunnelTypes: "gre"
  NeutronDpdkCoreList: "'2,3,22,23'"
  NeutronDpdkMemoryChannels: "4"
  NeutronDatapathType: "netdev"
  NeutronVhostuserSocketDir: "/var/run/openvswitch"
  NeutronDpdkSocketMemory: "'2048,2048'"
  NeutronDpdkDriverType: "vfio-pci"
  NovaReservedHostMemory: 4096
  NovaVcpuPinSet: ['12-21','24-87']
  NovaSchedulerDefaultFilters: "RamFilter,ComputeFilter,AvailabilityZoneFilter,ComputeCapabilitiesFilter,ImagePropertiesFilter,PciPassthroughFilter,NUMATopologyFilter,AggregateInstanceExtraSpecsFilter"
  ComputeKernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=64 intel_iommu=on isolcpus=2,3,22,23,12-87"

